description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: sh
    - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
      with:
        cache: 'yarn'
        node-version-file: '.node-version'
    - run: yarn install --immutable --mode=skip-build
      shell: sh
