description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: sh
    - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
      with:
        cache: 'yarn'
        node-version-file: '.node-version'
    - run: yarn install --immutable --mode=skip-build
      shell: sh
