name: lint

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/.eslintrc.yml"
      - .github/actions/setup-node/**
      - .github/workflows/eslint.yml
      - package.json
      - tsconfig.json
      - tsconfig.node.json
      - yarn.lock
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/setup-node
      - run: yarn lint
