name: yarn

on:
  push:
    paths-ignore:
      - .github/actions/setup-node/**
      - .github/workflows/yarn.yml
      - yarn.lock

concurrency: yarn

jobs:
  yarn:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: ./.github/actions/setup-node
