name: yarn

on:
  merge_group:
    types:
      - checks_requested
  push:
    paths:
      - .github/actions/setup-node/**
      - .github/workflows/yarn.yml
      - yarn.lock

concurrency: yarn

jobs:
  yarn:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - uses: ./.github/actions/setup-node
