name: yarn

on:
  merge_group:
    types:
      - checks_requested
  push:
    paths:
      - .github/actions/setup-node/**
      - .github/workflows/yarn.yml
      - yarn.lock

concurrency: yarn

jobs:
  yarn:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/setup-node
